services:
  db:
    container_name: room-reservation-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${DB_NAME:-roomreservation}
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

#  spring-boot-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: room-reservation
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME:-roomreservation}
#      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-admin}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-admin}
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    restart: on-failure

volumes:
  pgdata:
    driver: local